f_source_functions <- function() {
  ### Cette fonction load toutes les librairies et fonctions utilisées.
  library("xts")
  library("zoo")
  library("quantmod")
  library("TTR")
  library("openxlsx")
  library("readxl")
  library("writexl")
  library("PerformanceAnalytics")
  library("ggplot2")
  library("tidyverse")
  library("lubridate")
  library("stats")
  library("caret")
  library("glmnet")
  library("Metrics")
  library("R6")
  library("randomForest")
  
  source(here("Function", "f_get_and_clean_data.R"))
  source(here("Function", "f_build_strategies.R"))
  source(here("Function", "f_trading.R"))
  source(here("Function", "f_generate_reports.R"))
  source(here("Function", "f_create_training_data_classification.R"))
}